# AUTO-GENERATED by spnl-erb — DO NOT EDIT
class UsersIndexView
  def initialize(users, rendered_at)
      @users = users
      @rendered_at = rendered_at
  end

  def render
    _out = ""
    _out = _out + "<!DOCTYPE html>\n<html>\n<head>\n  <meta charset=\"utf-8\">\n  <title>Users — spnl-erb demo</title>\n  <style>\n    body { font-family: system-ui, sans-serif; max-width: 720px; margin: 2em auto; }\n    table { border-collapse: collapse; width: 100%; }\n    th, td { padding: 8px 12px; border-bottom: 1px solid #ddd; text-align: left; }\n    .badge { display: inline-block; padding: 2px 8px; border-radius: 4px; font-size: 0.8em; }\n    .admin { background: #d33; color: white; }\n    .user  { background: #888; color: white; }\n  </style>\n</head>\n<body>\n  <h1>Users ("
    _out = _out + (@users.length).to_s
    _out = _out + ")</h1>\n\n  "
    if @users.length == 0
    _out = _out + "  <p>No users.</p>\n  "
    else
    _out = _out + "  <table>\n    <thead><tr><th>#</th><th>Name</th><th>Email</th><th>Role</th></tr></thead>\n    <tbody>\n"
    i = 0
    @users.each do |u|
    i = i + 1
    _out = _out + "      <tr>\n        <td>"
    _out = _out + (i).to_s
    _out = _out + "</td>\n        <td>"
    _out = _out + (u.display_name).to_s
    _out = _out + "</td>\n        <td>"
    _out = _out + (u.email).to_s
    _out = _out + "</td>\n        <td>\n          "
    if u.admin?
    _out = _out + "          <span class=\"badge admin\">admin</span>\n          "
    else
    _out = _out + "          <span class=\"badge user\">user</span>\n          "
    end
    _out = _out + "        </td>\n      </tr>\n"
    end
    _out = _out + "    </tbody>\n  </table>\n  "
    end
    _out = _out + "\n  <p><small>Rendered at "
    _out = _out + (@rendered_at).to_s
    _out = _out + " by spnl-erb + Spinel AOT.</small></p>\n</body>\n</html>\n"
    _out
  end
end
