# AUTO-GENERATED by spnl-router — DO NOT EDIT
# source: SiteController
module SiteRouter
  def self.dispatch(path)
    c = SiteController.new
    # action が render_xxx 内で @site_name 等を参照する前に
    # set_chrome を空 default で先に呼んで ivar を確定させる.
    # (Spinel は nil ivar アクセスで segfault するため必須)
    c.set_chrome("", "")
    body = ""
    nav  = ""
    case path
    when "/"
      body = c.home; nav = "home"
    when "/users"
      body = c.users; nav = "users"
    else
      return "404"
    end
    c.set_chrome(nav, body)
    c.render_layout
  end
end
