# AUTO-GENERATED by spnl-erb — DO NOT EDIT
# mode: controller (reopen SiteController, ivar 直接参照)
# 利用 (controller 側):
#   class SiteController
#     def show
#       @posts = Post.all
#       @title = "Latest"
#       respond(render_home)
#     end
#   end
class SiteController
  def render_home
    _out = ""
    _out = _out + "<section>\n  <h1>"
    _out = _out + (@page_title).to_s
    _out = _out + "</h1>\n  <p>"
    _out = _out + (@message).to_s
    _out = _out + "</p>\n\n  <h2>Try the routes</h2>\n  <ul>\n    <li><a href=\"/site/\">/site/</a> — このページ</li>\n    <li><a href=\"/site/users\">/site/users</a> — User 一覧 (View+Model 実例)</li>\n  </ul>\n\n  <h2>How it's wired</h2>\n  <p>HTTP request <code>/site/...</code> が来ると httpd_async.rb は <code>SiteRouter.dispatch</code> に委譲.\n  生成された dispatcher は static <code>case/when</code> で action method を呼び, set_chrome + render_layout で wrap.\n  すべて AOT compile 後の単一バイナリ.</p>\n</section>\n"
    _out
  end
end
