# AUTO-GENERATED by spnl-erb — DO NOT EDIT
# mode: controller (reopen SiteController, ivar 直接参照)
# 利用 (controller 側):
#   class SiteController
#     def show
#       @posts = Post.all
#       @title = "Latest"
#       respond(render_layout)
#     end
#   end
class SiteController
  def render_layout
    _out = ""
    _out = _out + "<!DOCTYPE html>\n<html>\n<head>\n  <meta charset=\"utf-8\">\n  <title>"
    _out = _out + (@page_title).to_s
    _out = _out + " — "
    _out = _out + (@site_name).to_s
    _out = _out + "</title>\n  <style>\n    body { font-family: system-ui, sans-serif; max-width: 720px; margin: 2em auto; padding: 0 1em; line-height: 1.6; color: #222; }\n    nav { display: flex; gap: 1.5em; padding-bottom: 1em; border-bottom: 2px solid #333; margin-bottom: 1.5em; }\n    nav a { color: #07c; text-decoration: none; font-weight: 600; }\n    nav a.active { color: #c33; }\n    table { border-collapse: collapse; width: 100%; }\n    th, td { padding: 8px 12px; border-bottom: 1px solid #ddd; text-align: left; }\n    .badge { display: inline-block; padding: 2px 8px; border-radius: 4px; font-size: 0.8em; }\n    .admin { background: #d33; color: white; }\n    .user  { background: #888; color: white; }\n    footer { margin-top: 3em; padding-top: 1em; border-top: 1px solid #ddd; color: #888; font-size: 0.85em; }\n  </style>\n</head>\n<body>\n  <nav>\n    <a href=\"/site/\" class=\""
    _out = _out + (@active_nav == "home" ? "active" : "").to_s
    _out = _out + "\">Home</a>\n    <a href=\"/site/users\" class=\""
    _out = _out + (@active_nav == "users" ? "active" : "").to_s
    _out = _out + "\">Users</a>\n  </nav>\n\n  "
    _out = _out + (@content).to_s
    _out = _out + "\n\n  <footer>\n    <p>© "
    _out = _out + (@year).to_s
    _out = _out + " "
    _out = _out + (@site_name).to_s
    _out = _out + " · "
    _out = _out + (@site_tagline).to_s
    _out = _out + "</p>\n    <p>Routed by spnl-router · Rendered by spnl-erb · Compiled by Spinel</p>\n  </footer>\n</body>\n</html>\n"
    _out
  end
end
