# AUTO-GENERATED by spnl-erb — DO NOT EDIT
# mode: controller (reopen SiteController, ivar 直接参照)
# 利用 (controller 側):
#   class SiteController
#     def show
#       @posts = Post.all
#       @title = "Latest"
#       respond(render_users)
#     end
#   end
class SiteController
  def render_users
    _out = ""
    _out = _out + "<section>\n  <h1>Users ("
    _out = _out + (@users.length).to_s
    _out = _out + ")</h1>\n  <table>\n    <thead><tr><th>#</th><th>Name</th><th>Email</th><th>Role</th></tr></thead>\n    <tbody>\n"
    i = 0
    @users.each do |u|
    i = i + 1
    _out = _out + "      <tr>\n        <td>"
    _out = _out + (i).to_s
    _out = _out + "</td>\n        <td>"
    _out = _out + (u.display_name).to_s
    _out = _out + "</td>\n        <td>"
    _out = _out + (u.email).to_s
    _out = _out + "</td>\n        <td>\n"
    if u.admin?
    _out = _out + "          <span class=\"badge admin\">admin</span>\n"
    else
    _out = _out + "          <span class=\"badge user\">user</span>\n"
    end
    _out = _out + "        </td>\n      </tr>\n"
    end
    _out = _out + "    </tbody>\n  </table>\n</section>\n"
    _out
  end
end
